import { TeamMember } from "./team-member";


export const TEAM_COACH: TeamMember = {
  id: 100,
  fullName: 'Сергій Левченко',
  role: 'Coach',
  photoUrl: 'assets/team/coach.jpg',
  shortBio: 'Помогает команде расти: процессы, коммуникации, фокус на результат.',
  bio: 'Сергій — тренер команды. Помогает выстраивать взаимодействие, улучшать процессы, проводить ретро, формировать прозрачные договорённости и поддерживать устойчивый темп. Фокус — на эффективности и здоровой культуре.',
  location: 'Kyiv, UA',
  email: 'serhii.levchenko@example.com',
  telegram: '@coach_serhii',
  joinedAtIso: '2022-01-10T09:00:00Z',
  skills: ['Coaching', 'Facilitation', 'Communication', 'Delivery'],
  interests: ['Team Health', 'Continuous Improvement'],
};

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 1,
    fullName: 'Анна Коваленко',
    role: 'Frontend Engineer',
    photoUrl: 'assets/team/anna.jpg',
    shortBio: 'Angular + Material, UI/UX аккуратность, любит дизайн-системы.',
    bio: 'Отвечает за компонентный подход, архитектуру UI и качество интерфейса. Умеет быстро собирать прототипы и доводить до продакшена.',
    location: 'Kyiv, UA',
    email: 'anna.kovalenko@example.com',
    telegram: '@anna_k',
    joinedAtIso: '2024-06-10T09:00:00Z',
    skills: ['Angular', 'TypeScript', 'Angular Material', 'RxJS', 'SCSS'],
    interests: ['Design Systems', 'Accessibility', 'Motion'],
  },
  {
    id: 2,
    fullName: 'Максим Черненко',
    role: 'Product Designer',
    photoUrl: 'assets/team/max.jpg',
    shortBio: 'Проектирует флоу, прототипы, следит за консистентностью.',
    bio: 'Делает прототипирование, проводит UX-ревью, помогает команде держать единый стиль и понятные сценарии.',
    location: 'Lviv, UA',
    email: 'max.chernenko@example.com',
    telegram: '@max_design',
    joinedAtIso: '2023-11-01T10:00:00Z',
    skills: ['Figma', 'UX Research', 'Prototyping', 'Design Systems'],
    interests: ['User Interviews', 'Heuristics', 'Microcopy'],
  },
  {
    id: 3,
    fullName: 'Ірина Мельник',
    role: 'QA Engineer',
    photoUrl: 'assets/team/iryna.jpg',
    shortBio: 'Автотести, чек-листы, релизная дисциплина.',
    bio: 'Ведёт тестовую документацию, покрывает критические сценарии автотестами и помогает быстрее ловить регрессии.',
    location: 'Dnipro, UA',
    email: 'iryna.melnyk@example.com',
    joinedAtIso: '2024-02-15T10:00:00Z',
    skills: ['Test Planning', 'E2E', 'Playwright', 'Bug Triage'],
    interests: ['Quality Culture', 'Observability'],
  },
  {
    id: 4,
    fullName: 'Олег Сидоренко',
    role: 'Tech Lead',
    photoUrl: 'assets/team/oleh.jpg',
    shortBio: 'Архитектура, стандарты, ревью, помогает масштабироваться.',
    bio: 'Определяет техническое направление, менторит команду, выстраивает процессы и практики: code review, CI, договорённости по архитектуре.',
    location: 'Kyiv, UA',
    email: 'oleh.sydorenko@example.com',
    telegram: '@oleh_tl',
    joinedAtIso: '2022-09-05T08:30:00Z',
    skills: ['Architecture', 'Angular', 'Performance', 'CI/CD'],
    interests: ['Simplicity', 'DX', 'Engineering Management'],
  },
  {
    id: 5,
    fullName: 'Катерина Бойко',
    role: 'Project Manager',
    photoUrl: 'assets/team/kateryna.jpg',
    shortBio: 'Планирование, синхронизация, коммуникации, риски.',
    bio: 'Ведёт планирование, следит за дедлайнами, помогает команде держать фокус и прозрачность, управляет рисками и ожиданиями стейкхолдеров.',
    location: 'Odesa, UA',
    email: 'kateryna.boiko@example.com',
    joinedAtIso: '2023-03-20T09:30:00Z',
    skills: ['Planning', 'Stakeholder Management', 'Risk Management', 'Facilitation'],
    interests: ['Team Health', 'Process Improvement'],
  },
];
