import { TeamMember } from "./team-member";


export const TEAM_COACH: TeamMember = {
  id: 100,
  fullName: 'Михайло Петрушка, Юлія Малахова',
  role: 'Тренери команди',
  photoUrl: 'assets/coach.jpg',
  shortBio: 'Помогает команде расти: процессы, коммуникации, фокус на результат.',
  bio: 'Михайло і Юлія — тренеры команды. Помогают выстраивать взаимодействие, улучшать процессы, проводить ретро, формировать прозрачные договорённости и поддерживать устойчивый темп. Фокус — на эффективности и здоровой культуре.',
  location: 'Тернопіль, Україна',
  email: 'serhii.levchenko@example.com',
  telegram: '@coach_serhii',
  joinedAtIso: '2022-01-10T09:00:00Z',
  skills: ['Coaching', 'Facilitation', 'Communication', 'Delivery'],
  interests: ['Team Health', 'Continuous Improvement'],
};

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 1,
    fullName: 'Валерій Димитрієв',
    role: 'Інженер розробник',
    photoUrl: 'assets/dymytriiev.jpg',
    shortBio: 'Angular + Material, UI/UX, system design',
    bio: 'EPAM Systems Engineer, створює компоненти з урахуванням UX, accessibility та performance, допомагає команді дотримуватися єдиного стилю та зрозумілих сценаріїв.',
    location: 'Львів, Україна',
    email: 'valeriy.dmytriiev@gmail.com',
    telegram: '@valeriy_d',
    joinedAtIso: '2024-06-10T09:00:00Z',
    skills: ['Angular', 'TypeScript', 'Angular Material', 'RxJS', 'SCSS'],
    interests: ['Design Systems', 'Accessibility', 'Motion'],
  },
  {
    id: 2,
    fullName: 'Павло Соломенчук',
    role: 'Інженер розробник',
    photoUrl: 'assets/solomechuk.jpg',
    shortBio: '.Net, Azure, DevOps, CI/CD',
    bio: 'UiPath Developer, спеціаліст з .Net та Azure, відповідає за бекенд частину проєкту, інтеграції та налаштування CI/CD процесів.',
    location: 'Львів, Україна',
    email: 'pavlo.solomenchuk@gmail.com',
    telegram: '-',
    joinedAtIso: '2023-11-01T10:00:00Z',
    skills: ['Figma', 'UX Research', 'Prototyping', 'Design Systems'],
    interests: ['User Interviews', 'Heuristics', 'Microcopy'],
  },
  {
    id: 3,
    fullName: 'Максим Потапов',
    role: 'QA Engineer',
    photoUrl: 'assets/potapov.jpg',
    shortBio: 'Automation, E2E, Playwright, Test Planning',
    bio: 'LinkupST, QA Engineer, відповідає за якість продукту, розробляє та підтримує автоматизовані тести, планує тестування та співпрацює з командою для виявлення та усунення дефектів.',
    location: 'Тернопіль, Україна',
    email: 'max.potapov@gmail.com',
    joinedAtIso: '2024-02-15T10:00:00Z',
    skills: ['Test Planning', 'E2E', 'Playwright', 'Bug Triage'],
    interests: ['Quality Culture', 'Observability'],
  },
  {
    id: 4,
    fullName: 'Юрій Левко',
    role: 'Інженер розробник',
    photoUrl: 'assets/levko.jpg',
    shortBio: 'Fullstack, Architecture, CI/CD',
    bio: 'MarketBlitz Limited, Senior Software Engineer, відповідає за архітектуру додатку, розробку ключових функціональних можливостей та впровадження CI/CD практик у команді.',
    location: 'Kyiv, UA',
    email: 'yuriy.levko@gmail.com',
    telegram: '@oleh_tl',
    joinedAtIso: '2022-09-05T08:30:00Z',
    skills: ['Architecture', 'Angular', 'Performance', 'CI/CD'],
    interests: ['Simplicity', 'DX', 'Engineering Management'],
  },
];
