import { TeamMember } from "./team-member";

export const TEAM_COACHES: TeamMember[] = [
  {
    id: 101,
    fullName: "Юлія Малахова",
    role: "Тренерка команди",
    photoUrl: "assets/malahova.jpg",
    shortBio: "Коучинг, розвиток команди, комунікація та фокус на результат.",
    bio: "Юлія допомагає команді будувати здорові процеси, підтримує ефективну комунікацію та розвиток. Працює з фокусом на результат і стабільний темп.",
    location: "Тернопіль, Україна",
    email: "malahova@example.com",
    telegram: "@malahova",
    joinedAtIso: "2022-01-10T09:00:00Z",
    skills: ["Coaching", "Facilitation", "Communication", "Delivery"],
    interests: ["Team Health", "Continuous Improvement"],
  },
  {
    id: 102,
    fullName: "Михайло Петрушка",
    role: "Тренер команди",
    photoUrl: "assets/petrushka.jpg",
    shortBio: "Працює з процесами, мотивацією та узгодженням цілей команди.",
    bio: "Михайло допомагає команді тримати фокус, підсилює взаємодію та підтримує культуру прозорості. Орієнтується на стійкі процеси та якісний результат.",
    location: "Тернопіль, Україна",
    email: "petrushka@example.com",
    telegram: "@petrushka",
    joinedAtIso: "2022-01-10T09:00:00Z",
    skills: ["Coaching", "Facilitation", "Communication", "Delivery"],
    interests: ["Team Health", "Continuous Improvement"],
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 1,
    fullName: "Петро Соломечук",
    role: "Інженер розробник",
    photoUrl: "assets/solomechuk.jpg",
    shortBio: "Angular + Material, UI/UX, RxJS",
    bio: "Senior Frontend Engineer. Працює над інтерфейсами та компонентами, підтримує якість UI та продуктивність.",
    location: "Kyiv, UA",
    email: "solomechuk@example.com",
    telegram: "@solomechuk",
    joinedAtIso: "2024-06-10T09:00:00Z",
    skills: ["Angular", "TypeScript", "Angular Material", "RxJS", "SCSS"],
    interests: ["Design Systems", "Accessibility", "Motion"],
  },
  {
    id: 2,
    fullName: "Влад Потапов",
    role: "Інженер розробник",
    photoUrl: "assets/potapov.jpg",
    shortBio: "Fullstack, UI, інтеграції",
    bio: "Розробляє функціонал продукту, відповідає за якісні інтеграції, покращує UX у щоденних сценаріях.",
    location: "Lviv, UA",
    email: "potapov@example.com",
    telegram: "@potapov",
    joinedAtIso: "2023-11-01T10:00:00Z",
    skills: ["TypeScript", "Angular", "Node.js", "API"],
    interests: ["Product thinking", "DX"],
  },
  {
    id: 3,
    fullName: "Валерій Дмитрієв",
    role: "Інженер розробник",
    photoUrl: "assets/dymytriiev.jpg",
    shortBio: "UI, архітектура, флоу користувача",
    bio: "Працює над архітектурою, якістю коду та UX. Допомагає систематизувати підхід до компонентів і структури проекту.",
    location: "Kyiv, UA",
    email: "radolmilita@gmail.com",
    telegram: "@radolmilita",
    joinedAtIso: "2024-02-15T10:00:00Z",
    skills: ["Angular", "TypeScript", "Architecture", "Material"],
    interests: ["Performance", "UI patterns"],
  },
  {
    id: 4,
    fullName: "Юрій Левко",
    role: "Інженер розробник",
    photoUrl: "assets/levko.jpg",
    shortBio: "Fullstack, Architecture, CI/CD",
    bio: "MarketBlitz Limited, Senior Software Engineer. Відповідає за архітектуру, інтеграції та впровадження CI/CD практик.",
    location: "Kyiv, UA",
    email: "yuriy.levko@gmail.com",
    telegram: "@oleh_tl",
    joinedAtIso: "2022-09-05T08:30:00Z",
    skills: ["Architecture", "Angular", "Performance", "CI/CD"],
    interests: ["Simplicity", "DX", "Engineering Management"],
  },
];
